Ticket1276: Deleting all blocks also deletes all groups system test
ISISComputingGroup/ibex_system_tests pull request #11
Opened 2016-06-17 15:33 UTC by simonfernandes

ISISComputingGroup/IBEX/issues/1276

2016-06-21 13:07 UTC, AdrianPotter commented
[] Please move the test file from the "Context" folder to the "IBEX_System_Tests" folder
[] Add the new test to the AllTests suite
[] Check that the tests pass locally. Currently the test fails as part of the suite because the block added in "AddFirstBlock" is not removed as part of the test.
[] Check the [Jenkins PR](http://epics-jenkins.isis.rl.ac.uk/job/System_Tests_build_PR/) build passes

2016-10-07 15:53 UTC, John-Holt-Tessella commented
No longer have jenkins PR and don't need to remove block

2016-10-11 12:38 UTC, AdrianPotter requested changes
Very minor refactoring for loop please

2016-10-11 12:38 UTC, AdrianPotter commented on RCPTT_Tests/ConfigurationTests/DeletingAllBlocksDeletesAllGroups.test
> +delete_block "0"
We figured out how to do loops in RCPTT. See CurrentConfigNotInDeleteConfigDialog for example. Can we do that here please

2016-10-12 10:33 UTC, AdrianPotter approved these changes

2016-10-12 10:33 UTC, merged