Block format test
ISISComputingGroup/ibex_system_tests pull request #60
Opened 2017-06-14 14:59 UTC by Tom-Willemsen

### Description of work

Tests that blocks from SIMPLE IOC are formatted appropriately.

### To test

https://github.com/ISISComputingGroup/IBEX/issues/2377

---

#### Code Review

- [ ] Is the code of an acceptable quality?
- [ ] Does the code make use of existing procedures where appropriate?
- [ ] Do they test a minimal set of functionality and leave the gui as close as possible to its original state?
- [ ] Does the name of the tests reflect what is actually being tested?
- [ ] Has the [manual system tests spreadsheet](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Manual-system-tests) been updated to have entries equivalent to the system tests affected?
    - For example, remove manual tests that are covered by automated tests

### Functional Tests

- [ ] Do the new tests pass on a GUI build containing the fix?
- [ ] Do the new tests fail on a GUI build NOT containing the fix (e.g. master)?

2017-06-14 15:22 UTC, AdrianPotter commented
Under review

2017-06-14 15:33 UTC, AdrianPotter requested changes
A few suggestions for making the test more concise

2017-06-14 15:33 UTC, AdrianPotter commented on RCPTT_Tests/BlocksTests/BlocksAreFormattedCorrectly.test
> +	     	get-combo -after [get-label "Sim. Level"] | select RECSIM
I don't think this is needed. `SIMPLE` IOC doesn't connect to hardware, it's purely software, so works just fine in normal mode

2017-06-14 15:33 UTC, AdrianPotter commented on RCPTT_Tests/BlocksTests/BlocksAreFormattedCorrectly.test
> +	create_empty_config -config_name $configname
I don't think you need `-config_name` here

2017-06-14 15:33 UTC, AdrianPotter commented on RCPTT_Tests/BlocksTests/BlocksAreFormattedCorrectly.test
> +configure_simple_ioc
Why not do this as `with [new_config]` so you don't have two changes to the current configuration. It would keep the test length down a bit.

2017-06-14 15:33 UTC, AdrianPotter commented on RCPTT_Tests/BlocksTests/BlocksAreFormattedCorrectly.test
> + 		add_ioc -ioc_name "SIMPLE" -window $window
Perhaps use add_ioc_no_macros, and add an autostart parameter. Then the code is much simpler and you don't need to pass `window` around as an argument.

```
proc configure_simple_ioc [val name] {
	with [edit_current_config] {
		add_ioc_no_macros "SIMPLE" -auto_start true
 		add_blocks_to_simple_ioc
 		save_config
 	}
 }
 
proc add_blocks_to_simple_ioc {
 	add_block "LONG" "SIMPLE:LONG" 
 	add_block "INT" "SIMPLE:VALUE1"
 	add_block "P3" "SIMPLE:VALUE:P3"
 	add_block "P5" "SIMPLE:VALUE:P5"
 	add_block "STRING" "SIMPLE:HELLO"
}
```

```
// Add an IOC without macros
proc add_ioc_no_macros [val ioc_name] [val window -input true] [val auto_start -value false]{
	with $window {
		add_ioc $ioc_name
	}
	try -times 100 -delay 200 -command {
		with [get_ioc_dialog] {
			if [$auto_start | equals true] {
				get-button "Auto-Start" | check
			}
			get-button OK | check_enabled_and_click
		}
	}
}
```

2017-06-16 11:04 UTC, Tom-Willemsen commented
Ready for re-review

2017-06-19 09:30 UTC, AdrianPotter commented
Under review

2017-06-19 10:06 UTC, merged